# -*- coding:utf-8 -*-
# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields
)
from swagger_marshmallow_codegen.fields import DateTime


class Movies(Schema):
    title = fields.String()
    year = fields.Integer()
    info = fields.Field('Info')


class Info(Schema):
    actors = fields.List(fields.String())
    directors = fields.List(fields.String())
    genres = fields.List(fields.String())
    image_url = fields.String()
    plot = fields.String()
    rank = fields.Integer()
    rating = fields.Float()
    release_date = DateTime()
    running_time_secs = fields.Integer()


class Failure(Schema):
    error_message = fields.String()
    error_code = fields.String()

